### ISSUE TITLE
Data for experiments not found after running run_docker.sh

### ISSUE THREAD

**Issue by varungohil** [barabanshek/IAA_benchmarking#2]
I ran sudo ./run_docker.sh 1  and generated results.csv.
However, at the end I get

![image](https://github.com/barabanshek/IAA_benchmarking/assets/25960514/c5ac5925-a433-4e83-937a-267211bb143f)

On manually inspecting it seems like data is present in results.csv
I think the path to results.csv file in plotting script is wrong.

**Comment by barabanshek** [comment]
Please,  test https://hub.docker.com/repository/docker/barabanshik/sabre_iaa_benchmark/general

**Comment by barabanshek** [comment]
Done.
